# pubspec.yaml
name: macro_union_types
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer: 
  analyzer_plugin:
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder:
